name: Test Windows Cross Compile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            gcc-mingw-w64-x86-64 \
            g++-mingw-w64-x86-64 \
            ninja-build \
            pkg-config \
            python3-pip

          pip3 install meson

      - name: Check tools
        run: |
          x86_64-w64-mingw32-gcc --version
          meson --version
          ninja --version

      - name: Configure
        run: |
          meson setup build \
            --cross-file cross-windows-x86_64.ini

      - name: Build
        run: |
          meson compile -C build

      - name: Check executable
        run: |
          file build/cross-test.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cross-test-windows-x64
          path: build/cross-test.exe